// <auto-generated />
namespace CampManagerWebUI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class InvoicePosition_pricepPrecision : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InvoicePosition_pricepPrecision));
        
        string IMigrationMetadata.Id
        {
            get { return "201607021157071_InvoicePosition_pricepPrecision"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
