// <auto-generated />
namespace CampManagerWebUI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MealBid_expend_people : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MealBid_expend_people));
        
        string IMigrationMetadata.Id
        {
            get { return "201607181719218_MealBid_expend_people"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
