// <auto-generated />
namespace CampManagerWebUI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SeasonOrganization_active : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SeasonOrganization_active));
        
        string IMigrationMetadata.Id
        {
            get { return "201906090901139_SeasonOrganization_active"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
