// <auto-generated />
namespace CampManagerWebUI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NewTables_UserOrganization_UserEmailAllow : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewTables_UserOrganization_UserEmailAllow));
        
        string IMigrationMetadata.Id
        {
            get { return "201906211515548_NewTables_UserOrganization_UserEmailAllow"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
