// <auto-generated />
namespace CampManagerWebUI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NewTable_UserSettings : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewTable_UserSettings));
        
        string IMigrationMetadata.Id
        {
            get { return "201906211524473_NewTable_UserSettings"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
